on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

name: run tests
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install UI Deps
      run: npm ci
    - name: Fake Install flux
      run: mkdir -p pkg/flux/bin && touch pkg/flux/bin/flux
    - name: Build UI Assets
      run: make cmd/wego/ui/run/dist/index.html
    - name: Run linters
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.29
        args: --timeout=600s
    - name: Check Format
      run: make check-format

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Clean
      run: make clean
    - name: build
      run: make wego
    - name: Store wego binaries
      uses: actions/upload-artifact@v2
      with:
          name: wego-binaries
          path: bin
          retention-days: 1

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install lcov
      run:  sudo apt-get install -y lcov
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install UI Deps
      run: npm ci
    # - name: NPM Audit
    #   run: npm audit
    - name: Build UI Assets
      run: make cmd/wego/ui/run/dist/main.js
    - name: Set up kubebuilder
      uses: fluxcd/pkg/actions/kubebuilder@main
    - name: Set up flux dir but let dependencies install flux
      run: mkdir -p pkg/flux/bin && tools/download-deps.sh $PWD/tools/dependencies.toml
    - name: Unit Tests with Coverage
      run: make coverage/merged.lcov
      env:
        KUBEBUILDER_ASSETS: ${{ github.workspace }}/kubebuilder/bin
    - name: Coveralls
      uses: coverallsapp/github-action@v1.1.2
      with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: merged.lcov
    - name: Library Integration Test
      env:
        GITHUB_TOKEN: "${{ secrets.WEAVE_GITOPS_TEST_WEAVEWORKS_WEAVE_GITOPS_BOT_TOKEN }}"
      run: make lib-test
  smoke-tests:
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 60
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.3
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Kubernetes
      uses: engineerd/setup-kind@v0.5.0
      with:
        name: "${{ format('katc-{0}', github.run_id) }}"
        version: "v0.11.0"
        image: kindest/node:v1.20.7
        config: "./test/acceptance/test/configs/kind-config.yaml"
    - name: Kind-check
      run: |
       kubectl get pods -A
    - name: Download wego binaries
      uses: actions/download-artifact@v2
      with:
        name: wego-binaries
        path: bin
    - name: Change bin permissions
      run: |
        chmod +x bin/wego
        ls -la bin
    - name: Download dependecies
      run: |
        make dependencies
    - name: Set up ssh agent
      uses: webfactory/ssh-agent@v0.5.2
      with:
        ssh-private-key: ${{ secrets.WEAVE_GITOPS_TEST_WEAVEWORKS_WEAVE_GITOPS_BOT_SSH_KEY }}
    - name: Configure git settings
      run: |
        git config --global init.defaultBranch main
        git config --global user.email "weave-test-user@example.com"
        git config --global user.name "Testy McTestFace"
        git config --global url.ssh://git@github.com/.insteadOf https://github.com/
    - name: Run smoke tests from acceptance suite
      env:
        GITHUB_ORG: weaveworks-gitops-test
        GITHUB_TOKEN: "${{ secrets.WEAVE_GITOPS_TEST_WEAVEWORKS_WEAVE_GITOPS_BOT_TOKEN }}"
        GITHUB_KEY: "${{ secrets.WEAVE_GITOPS_TEST_WEAVEWORKS_WEAVE_GITOPS_BOT_SSH_KEY }}"
      run: |
        export WEGO_BIN_PATH=$(pwd)/bin/wego
        export CLUSTER_PROVIDER=kubectl
        export DELETE_WEGO_RUNTIME_ON_EACH_TEST=true
        go get github.com/onsi/ginkgo/ginkgo
        go get github.com/onsi/gomega
        ginkgo --focus=SmokeTest --randomizeSuites --reportFile=$(pwd)/test-results/smoke-test-results.xml -v ./test/acceptance/test/...
  acceptance-tests:
    runs-on: ubuntu-latest
    needs: [lint, build, test]
    timeout-minutes: 90
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Kubernetes
      uses: engineerd/setup-kind@v0.5.0
      with:
        name: "${{ format('katc-{0}', github.run_id) }}"
        version: "v0.11.0"
        image: kindest/node:v1.20.7
        config: "./test/acceptance/test/configs/kind-config.yaml"
    - name: Kind-check
      run: |
       kubectl get pods -A
    - name: Download wego binaries
      uses: actions/download-artifact@v2
      with:
        name: wego-binaries
        path: bin
    - name: Change bin permissions
      run: |
        chmod +x bin/wego
        ls -la bin
    - name: Download dependecies
      run: |
        make dependencies
    - name: Set up ssh agent
      uses: webfactory/ssh-agent@v0.5.2
      with:
        ssh-private-key: ${{ secrets.WEAVE_GITOPS_TEST_WEAVEWORKS_WEAVE_GITOPS_BOT_SSH_KEY }}
    - name: Configure git settings
      run: |
        git config --global init.defaultBranch main
        git config --global user.email "weave-test-user@example.com"
        git config --global user.name "Testy McTestFace"
        git config --global url.ssh://git@github.com/.insteadOf https://github.com/
    - name: Run Full Acceptance Suite
      env:
        GITHUB_ORG: weaveworks-gitops-test
        GITHUB_TOKEN: "${{ secrets.WEAVE_GITOPS_TEST_WEAVEWORKS_WEAVE_GITOPS_BOT_TOKEN }}"
        GITHUB_KEY: "${{ secrets.WEAVE_GITOPS_TEST_WEAVEWORKS_WEAVE_GITOPS_BOT_SSH_KEY }}"
      run: |
        export PATH=${PATH}:`go env GOPATH`/bin
        export WEGO_BIN_PATH=$(pwd)/bin/wego
        export CLUSTER_PROVIDER=kubectl
        go get github.com/onsi/ginkgo/ginkgo
        go get github.com/onsi/gomega/...
        ginkgo --randomizeSuites --reportFile=$(pwd)/test-results/smoke-test-results.xml -v ./test/acceptance/test/...